### ISSUE TITLE
Getting Error while testing url 

### ISSUE THREAD

**Issue by rahul199300** [Stuub/Helios#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Helios/helios.py", line 751, in <module>
    main()
  File "/root/Helios/helios.py", line 727, in main
    scanner = XSSScanner(target, args.browser, args.headless, args.threads, 
  File "/root/Helios/helios.py", line 113, in __init__
    self.driver = self.setup_driver()
  File "/root/Helios/helios.py", line 133, in setup_driver
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by Stuub** [comment]
Geckodriver must be in path, it's likely you haven't got it installed.

Simple fix :) 

1. Go to https://github.com/mozilla/geckodriver/releases

2. Download Geckodriver

3. Move Geckodriver to location in $PATH - for Linux this is /usr/local/bin

Should work perfectly after that.

Let me know if you need anymore help

**Comment by Stuub** [comment]
Added a more automated fix for this with webdriver explicit definitions, users shouldn't have this issue going forward :)
